spring:
  h2: # 수정 필요
    console:
      enabled: true
      path: /h2-console
  datasource: # 수정 필요
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
logging:
  level:
    root: error
# 미디어 서버와 통신하기 위한 url : ex) http://localhost:8080
media-server:
  url: {media-server-url}